[log]
access.level = "debug"
access.path = "log/access.log"
error.path = "/var/log/rs_proxy/error.log"

[inbound] #入站配置
protocol = "socks5"
port = 1080
# uid="" #如果配置了认证，则需要将此行注释取消，并填写对应的值
# pwd="" #同上一行

[dns]
resolver = "local"
server = [] #这个server在此处要为空，因为域名：dev.ubuntu是配置在local host文件中，所以必须使用local进行解析

[[outbounds]]
name = "proxy"
protocol = "ethan"
uid = "" #服务端认证密码
pwd = "" #服务端认证账户
port = 1080 #服务端监听端口
addr = "" #服务端认证地址，如使用tls，则需要填写域名
crt_path = "" #服务端根证书文件路径，支持相对路径和绝对路径，如果是系统预埋的证书，则留空。如果该文件不存在，则留空，但该行必须存在，不存在的话则会被认为不使用tls

[[outbounds]]
name = "direct"
protocol = "direct"

[[routes]]
to = "direct" # to的名字需要与outbounds中的name匹配
rule = "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16"
rule_type = "CIDR"

[[routes]]
to = "direct"
rule = "CN"
rule_type = "GeoIP:country"

[[routes]]
to = "direct"
rule = "AS4134,AS4837,AS9808,AS24153,AS37963,AS45090,AS136907,AS38355,AS55967"
rule_type = "GeoIP:asn"

[[routes]]
to = "proxy"
rule = "*"
rule_type = "default"