[log]
access.level = "info"
access.path = "log/access.log"
error.path = "/var/log/rs_proxy/error.log"


[inbound] #入站配置
protocol = "ethan" 
port = 10800
uid = "" #服务端认证密码，需要与客户端保持一致
pwd = "" #服务端认证用户，需要与客户端保持一致

[inbound.tls] #服务端tls配置，推荐使用tls进行加密，防止被封
crt_path = "" #公钥证书链文件路径
key_path = "" #私钥文件路径
domain_name = "" #域名

[[outbounds]]
name="direct"
protocol = "direct"

[[routes]]
to="direct"
rule="*"
rule_type="default"
