[log]
access.level = "info"
access.path = "log/server_access.log"
error.path = "/var/log/rx_proxy/error.log"

[inbound]
protocol = "ethan"
port = 10800
uid = "ethan.wang"
pwd = "pass01!"

[inbound.tls]
crt_path = "localhost.crt"
key_path = "localhost.key"
domain_name = "localhost"

[outbound]
protocol = "freedom"
