[log]
access.level = "info"
access.path = "log/access.log"
error.path = "/var/log/rs_proxy/error.log"


[inbound]
protocol = "ethan"
port = 10800
uid = "ethan.wang"
pwd = "pass01!"

[inbound.tls]
crt_path = "localhost.crt"
key_path = "localhost.key"
domain_name = "localhost"

[[outbounds]]
name="direct"
protocol = "direct"

[[routes]]
to="direct"
rule="*"
rule_type="default"
